name: Generate Edition JSON

on:
  push:
    paths:
      - 'links.txt'

permissions:
  contents: write   # ðŸ”¥ ESTO ES LA CLAVE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
          pip install requests beautifulsoup4 openai

      - name: Run script
        run: python generate.py

      - name: Commit and push edition.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add edition.json
          git commit -m "Auto generate edition.json" || echo "No changes to commit"
          git push
